### PR TITLE
Veto support for constraints

### PR DESCRIPTION
**Pull request by samcday**
Hi Geoff,

One more pull request for you, this will probably be the last one for now!

This patch gives constraints the ability to **veto** any further constraints from validating a field. This concept is something that isn't actually possible in standard Grails custom validators (to my knowledge), but does exist and is used in the grails core - primarily for things like the nullable constraint.

If you're wondering where something like vetoing might be handy, consider this:

```
class Foo {
    String date

    static constraints = {
        date(validDate: true, validation: { val ->
            // Some code to make sure the date is in
            // the future, or something.
        }
    }
}

// ... 

class ValidDateConstraint {
    static vetoer = true

    def validate = { val ->
        if(!parseDate(val)) {
            veto = true
            return false
        }
    }
}
```

As you can see, the ValidDateConstraint has indicated that it wishes to be able to veto subsequent constraints, and has exercised that veto power when it determines that a date isn't valid. This means that the custom validation written in Foo constraints will not execute _at all_ unless a valid date has been provided. Without vetoing, if a user were to provide an invalid date, they would receive two errors, one for the fact that they have an invalid date, and another stating that the (not yet valid) date is not in the future.

I feel that exposing veto capabilities to Constraints makes them much more composable, you could have a group of custom validations that run against a single field and work well together. Of course, sometimes it might make sense to present multiple validation fails on a single field, if the errors are pertinent enough. Veto support just gives developers the flexibility to decide that for themselves.

The code is commented and has a test written for it. Let me know if you need anything else, or want to discuss this concept further.

### CODE REVIEW

**Comment by geofflane** [comment]
Nullable might be a special case in the Grails code (not sure off hand, I'd need to look into it further). I'm guessing that vetoing depends on the order in which the Constraints are defined? So that a vetoer at the end has no effect on the previous constraints?

I'm not sure how I feel about that. It definitely gives the developer the control, but I'm wondering if depending on the ordering of the constraints is too subtle? It also assumes that the ordering that the constraints are executed in Grails is fixed based on the order that their defined in the domain. I'm not sure if that's an explicit contract or not.

Let me know what your thoughts are. I'll think on this a bit more.

**Comment by samcday** [comment]
Geoff,

Constraints definitely execute in the order they're defined, at least from the anecdotal evidence I've gathered from using Grails 2 and examining the source for GrailsDataBinder. It's interesting you should raise the concern that this doesn't seem to be an explicit obligation of the framework, I can't find it mentioned anywhere in the documentation either.

There is another strange subtlety with vetoing constrains too, say you have validation defined like this:

```
myField(constraint1: true, constraint2: true, vetoingConstraint1: true,
    vetoingConstraint2: true, constraint3: true)
```

Vetoing constraints get brought to the front and executed first, then non vetoing constraints execute only if none of the former exercised veto power. So the order of constraints would be this:
- vetoingConstraint1
- vetoingConstraint2
- constraint1
- constraint2
- constraint3

I don't know if this all that bad though, nothing a small amount of well-written documentation can't fix (which I'm happy to do if you want to accept this patch). Vetoing constraints are definitely useful though, the project we're using your excellent library in has already benefitted from them in several places. If used right I believe they increase code-readability, not detract from it.

**Comment by cdeszaq** [comment]
I would vote _against_ the idea of having a constraint impact other constraints implicitly. Not only would that require the ordering of constraints to matter, but it introduces a level of complexity and coupling that I don't think is worth it.

Instead, I think it should be up to each individual constraint to determine what it's "preconditions" are and if they are not met, to simply return `null`, which indicates neither valid nor invalid but says simply "I can't validate this either way."

Keeping constraints as mix/match-able and decoupled as possible is critical.

**Comment by samcday** [comment]
@cdeszaq, you're spot on tbh. initially I was using veto in a custom build of `constraints`, but have since realized it was a bad idea, it's quite brittle and the approach you outlined is what we ended up going for anyway.

I'll close this pull request now!

**Pull request closed without merging**
